---
- name: Run a webhook listener service
  hosts: all
  sources:
    - ansible.eda.webhook:
  rules:
    - name: Webhook ping pong debug
      condition: event.payload.ping == "pong"
      action:
        debug:
          msg: "I'm alive!"
  execution_strategy: "parallel"
